name: Build and Deploy

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    # Node 24 for all actions in this job
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn build
        env:
          CI: true # silent CI warnings during build

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/dev'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
